version: "3.7"
services:
  app:
    build: .
    restart: always
    ports:
      - "8989:8080"
    networks:
      - todo-list-net
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/todo_list_db?allowPublicKeyRetrieval=true
    depends_on:
      - mysqldb

  mysqldb:
    image: "mysql:8.0"
    restart: always
    networks:
      - todo-list-net
    environment:
      MYSQL_DATABASE: todo_list_db
      MYSQL_USER: todo
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: mysql

networks:
  todo-list-net: